spring.application.name=caso-de-uso-2

# Configurações do MQTT
mqtt.broker=tcp://localhost:1883
mqtt.client-id=spring-client
mqtt.topic=teste
mqtt.qos=1

# Configurações do InfluxDB
influx.url=http://localhost:8086
influx.token=yiwyHXqyb7P9D906CcKifhRJ-MQtlIlXkgaHKdVXsrNDVaNpj9hoXBRuDSrT8iAa1sMGlJNwTnTlChLC3VhOCQ==
influx.org=if
influx.bucket=caso_uso_2

# Configurações do Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=josevictor12